# Port du config server
server.port=8888

# Profil actif
spring.profiles.active=native,dev

# Emplacement EXACT du dépôt local
spring.cloud.config.server.native.search-locations=file:C:/Users/HP/Desktop/ReservationApp/reservation_system/config-server/config-repo/

# Actuator
management.endpoints.web.exposure.include=*

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.fail-fast=false
spring.application.name=config-service
