# Port du config server
server.port=8888

# Profil actif
spring.profiles.active=native,dev

# Emplacement EXACT du dépôt local
spring.cloud.config.server.native.search-locations=file:/config-repo/

# Actuator
management.endpoints.web.exposure.include=*



spring.cloud.config.fail-fast=false
spring.application.name=config-service
