# Port du Eureka Server
server.port=8761

# Nom du service
spring.application.name=discovery-service

# Configuration Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
