# ===============================
# Application
# ===============================
spring.application.name=API-GATEWAY
server.port=8080

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Routes du Gateway
# ===============================
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=resource-service
spring.cloud.gateway.routes[1].uri=lb://RESOURCE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/resources/**

spring.cloud.gateway.routes[2].id=reservation-service
spring.cloud.gateway.routes[2].uri=lb://RESERVATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/reservations/**

# ===============================
# Logging
# ===============================
logging.level.org.springframework.cloud.gateway=INFO
