# ------------------------------
# Port du service
# ------------------------------
server.port=8082
spring.application.name=resource-service
# ------------------------------
# Base de données MySQL
# ------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/resource_db
spring.datasource.username=root
spring.datasource.password=imrane
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------
# JPA / Hibernate
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ------------------------------
# Eureka Client
# ------------------------------
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


jwt.secret=MaCleSuperSecretePourJWT1234567890ABCDEFGH1234567890
